# Generated by Django 2.0 on 2018-01-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='sector_ref',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Sector Ref. Number'),
        ),
    ]
