# Generated by Django 2.0 on 2018-01-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_auto_20180101_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='letter_desc',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
