# Generated by Django 2.0 on 2018-01-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0003_auto_20180106_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lhistory',
            name='desc',
            field=models.CharField(max_length=300, verbose_name='Description'),
        ),
    ]
