# Generated by Django 2.0 on 2018-01-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0004_auto_20180106_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='letter_date',
            field=models.DateField(verbose_name='Letter Date'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_received',
            field=models.DateField(verbose_name='Letter Received'),
        ),
    ]
