# Generated by Django 2.0 on 2018-01-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0005_auto_20180108_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='letter',
            name='assigned_to',
            field=models.ManyToManyField(to='letter.LAssignTo'),
        ),
    ]
